./../src/core/define.sv
./../src/core/pc_counter.sv
./../src/core/if2id.sv
./../src/core/decode.sv
./../src/core/id2ex.sv
./../src/core/execute.sv
./../src/core/register.sv
./../src/core/riscv.sv
./../src/mem/prog_ram.sv
./../src/mem/data_ram.sv
./tb/tb_riscv_core.sv