`timescale 1ns / 1ps
`default_nettype wire
import riscv_pkg::*;
// ============================================================
// Module: id2ex
// Description:
//   Pipeline register between ID and EX stages.
//
// Responsibilities:
//   - Register original data signals: valid/pc/instr/op1/op2/store_data.
//   - Register all control signals generated by decode.
//   - On reset/flush, insert a safe bubble.
//
// Bubble safety:
//   - One canonical all-zero value covers every packet field.
//   - Reset, flush, and an invalid input all produce that same value.
//   - No register, CSR, memory, redirect, or exception control survives.
// ============================================================
module id2ex (
  input  logic        clk_i,
  input  logic        rst_ni,
  input  logic        flush_i,
  input  logic        stall_i,
  
  // 结构体输入：替代原本的几十根散线
  input  id_ex_pkt_t  pkt2ex_i,
  
  // 结构体输出
  output id_ex_pkt_t  pkt2ex_o
);

  id_ex_pkt_t pkt2ex_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      pkt2ex_q <= ID_EX_PKT_BUBBLE;
    end
    else if (flush_i) begin
      pkt2ex_q <= ID_EX_PKT_BUBBLE;
    end
    else if (!stall_i) begin
      if (pkt2ex_i.valid)
        pkt2ex_q <= pkt2ex_i;
      else
        pkt2ex_q <= ID_EX_PKT_BUBBLE;
    end
  end

  assign pkt2ex_o = pkt2ex_q;

`ifndef SYNTHESIS
  always @(negedge clk_i) begin
    if (rst_ni && !pkt2ex_q.valid) begin
      assert (pkt2ex_q === ID_EX_PKT_BUBBLE)
        else $error("ID/EX invalid packet is not the canonical bubble");
    end
  end
`endif

endmodule
`default_nettype wire
