`timescale 1ns / 1ps
`default_nettype wire
import riscv_pkg::*;
// ============================================================
// Module: id2ex
// Description:
//   Pipeline register between ID and EX stages.
//
// Responsibilities:
//   - Register original data signals: valid/pc/instr/op1/op2/store_data.
//   - Register all control signals generated by decode.
//   - On reset/flush, insert a safe bubble.
//
// Bubble safety:
//   - No register write (rf.we = 0).
//   - No memory write (mem_req = 0).
//   - No branch/jump redirect (branch/jump = NONE).
//   - No false exception/halt trigger (exc = 0).
//   - Inject INST_NOP to prevent illegal instruction decoding downstream.
// ============================================================
module id2ex (
  input  logic        clk_i,
  input  logic        rst_ni,
  input  logic        flush_i,
  input  logic        stall_i,
  
  // 结构体输入：替代原本的几十根散线
  input  id_ex_pkt_t  pkt2ex_i,
  
  // 结构体输出
  output id_ex_pkt_t  pkt2ex_o
);

  id_ex_pkt_t pkt2ex_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      // ------------------ 复位：注入安全气泡 ------------------
      pkt2ex_q.valid             <= 1'b0;
      pkt2ex_q.pc                <= '0;
      pkt2ex_q.instr             <= INST_NOP;  // 安全的 NOP 指令
      pkt2ex_q.rf.we             <= 1'b0;      // 禁止写寄存器
      pkt2ex_q.rf.addr           <= 5'd0;
      pkt2ex_q.ex_data           <= '0;        // op1, op2, imm, store_data 清零
      
      // 控制信号全部置为安全的无效状态
      pkt2ex_q.ex_ctrl.alu_op    <= ALU_NONE;
      pkt2ex_q.ex_ctrl.branch_op <= BR_NONE;
      pkt2ex_q.ex_ctrl.jump_op   <= JMP_NONE;
      pkt2ex_q.ex_ctrl.mem_req   <= 1'b0;
      pkt2ex_q.ex_ctrl.mem_we    <= 1'b0;
      pkt2ex_q.ex_ctrl.mem_size  <= MEM_SIZE_WORD;
      pkt2ex_q.ex_ctrl.mem_unsigned <= 1'b0;
      pkt2ex_q.ex_ctrl.wb_sel    <= WB_NONE;
      pkt2ex_q.ex_ctrl.muldiv_valid <= 1'b0;
      pkt2ex_q.ex_ctrl.muldiv_op <= MULDIV_NONE;
      
      // 异常信号清零
      pkt2ex_q.exc.illegal_instr <= 1'b0;
      pkt2ex_q.exc.ecall         <= 1'b0;
      pkt2ex_q.exc.ebreak        <= 1'b0;
      
      // 冒险辅助信号清零
      pkt2ex_q.use_rs1           <= 1'b0;
      pkt2ex_q.use_rs2           <= 1'b0;
    end
    else if (flush_i) begin
      // ------------------ 冲刷：同样注入安全气泡 ------------------
      pkt2ex_q.valid             <= 1'b0;
      pkt2ex_q.pc                <= '0;
      pkt2ex_q.instr             <= INST_NOP;
      pkt2ex_q.rf.we             <= 1'b0;
      pkt2ex_q.rf.addr           <= 5'd0;
      pkt2ex_q.ex_data           <= '0;
      pkt2ex_q.ex_ctrl.alu_op    <= ALU_NONE;
      pkt2ex_q.ex_ctrl.branch_op <= BR_NONE;
      pkt2ex_q.ex_ctrl.jump_op   <= JMP_NONE;
      pkt2ex_q.ex_ctrl.mem_req   <= 1'b0;
      pkt2ex_q.ex_ctrl.mem_we    <= 1'b0;
      pkt2ex_q.ex_ctrl.mem_size  <= MEM_SIZE_WORD;
      pkt2ex_q.ex_ctrl.mem_unsigned <= 1'b0;
      pkt2ex_q.ex_ctrl.wb_sel    <= WB_NONE;
      pkt2ex_q.ex_ctrl.muldiv_valid <= 1'b0;
      pkt2ex_q.ex_ctrl.muldiv_op <= MULDIV_NONE;
      pkt2ex_q.exc.illegal_instr <= 1'b0;
      pkt2ex_q.exc.ecall         <= 1'b0;
      pkt2ex_q.exc.ebreak        <= 1'b0;
      pkt2ex_q.use_rs1           <= 1'b0;
      pkt2ex_q.use_rs2           <= 1'b0;
    end
    else if (!stall_i) begin
      // ------------------ 正常流动：整体打包锁存 ------------------
      // 一行代码替代原本几十行的 assign
      pkt2ex_q <= pkt2ex_i;           
    end
  end

  assign pkt2ex_o = pkt2ex_q;

endmodule
`default_nettype wire